config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  get "carts/delete_cart/:id" => "carts#delete_cart"
  # get 'store/index'

  resources :halls
  # devise_for :users, :path => '/', controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "/admin" do
    resources :events
    resources :user, :controller => "user"
  end

  resources :events do
    resources :uploads
    resources :tickets
    resources :discounts
  end


  resources :payments

  get "molpay" => "payments#pay_with_molpay"

  post "/payments/:id" => "payments#show"
  post "/hook" => "payments#hook"

  get "/my_tickets" => "tickets#my_tickets"

  get "/assign_tickets" => "tickets#assign_tickets"

  post "/special_checkout" => "line_items#special_checkout"

  put "/subcurator_tickets" => "tickets#subcurator_tickets"

  put "/ticket_update_name" => "tickets#ticket_update_name"

  get "/tickets_customization" => "tickets#tickets_customization"

  get "/my_invoices" => "payments#my_invoices"

  get "/faq" => "store#faq"

  get "store/venue" => "store#venue"

  get "/print_tickets" => "tickets#print_tickets"

  root :to => 'store#index' , :as => 'store'

end

app/models/hall.rb
class Hall < ActiveRecord::Base
  has_many :events

  has_attached_file :seat_view, styles: { small: "64x64", med: "100x100", large: "200x200" }

  validates_attachment :seat_view, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates_presence_of :name, :description

end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  load_and_authorize_resource
  before_action :set_hall, only: [:show, :edit, :update, :destroy]

  # GET /halls
  # GET /halls.json
  def index
    @halls = Hall.all
  end

  # GET /halls/1
  # GET /halls/1.json
  def show
  end

  # GET /halls/new
  def new
    @hall = Hall.new
  end

  # GET /halls/1/edit
  def edit
  end

  # POST /halls
  # POST /halls.json
  def create
    @hall = Hall.new(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to halls_url, notice: 'Hall was successfully created.' }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /halls/1
  # PATCH/PUT /halls/1.json
  def update
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to halls_url, notice: 'Hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /halls/1
  # DELETE /halls/1.json
  def destroy
    @hall.destroy
    respond_to do |format|
      format.html { redirect_to halls_url, notice: 'Hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @hall = Hall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_params
      params.require(:hall).permit(:name, :description, :total_seat, :seat_view)
    end
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/views/halls/_form.html.erb
<%= simple_form_for(@hall) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :total_seat %>
    <%= f.input :seat_view %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/halls/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<h1>Editing Hall</h1>

<%= render 'form' %>

<%= link_to 'Show', @hall %> |
<%= link_to 'Back', halls_path %>
</div>

app/views/halls/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<%= link_to 'New Hall', new_hall_path, class: 'btn btn-default' %>
<%= link_to 'Events', events_path, class: 'btn btn-default' %>

<h1>Halls</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Total seat</th>
      <th>Seat view</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @halls.each do |hall| %>
      <tr>
        <td><%= hall.name %></td>
        <td><%= hall.description %></td>
        <td><%= hall.total_seat %></td>
        <td><%= link_to image_tag(hall.seat_view.url(:small)), hall.seat_view.url %></td>
        <td><%= link_to 'Show', hall %></td>
        <td><%= link_to 'Edit', edit_hall_path(hall) %></td>
        <td><%= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/halls/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
<h1>New Hall</h1>

<%= render 'form' %>

<%= link_to 'Back', halls_path %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/halls/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<p>
  <strong>Name:</strong>
  <%= @hall.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hall.description %>
</p>

<p>
  <strong>Total seat:</strong>
  <%= @hall.total_seat %>
</p>

<%= link_to 'Edit', edit_hall_path(@hall) %> |
<%= link_to 'Back', halls_path %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>