config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  get "carts/delete_cart/:id" => "carts#delete_cart"
  # get 'store/index'

  resources :halls
  # devise_for :users, :path => '/', controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "/admin" do
    resources :events
    resources :user, :controller => "user"
  end

  resources :events do
    resources :uploads
    resources :tickets
    resources :discounts
  end


  resources :payments

  get "molpay" => "payments#pay_with_molpay"

  post "/payments/:id" => "payments#show"
  post "/hook" => "payments#hook"

  get "/my_tickets" => "tickets#my_tickets"

  get "/assign_tickets" => "tickets#assign_tickets"

  post "/special_checkout" => "line_items#special_checkout"

  put "/subcurator_tickets" => "tickets#subcurator_tickets"

  put "/ticket_update_name" => "tickets#ticket_update_name"

  get "/tickets_customization" => "tickets#tickets_customization"

  get "/my_invoices" => "payments#my_invoices"

  get "/faq" => "store#faq"

  get "store/venue" => "store#venue"

  get "/print_tickets" => "tickets#print_tickets"

  root :to => 'store#index' , :as => 'store'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tickets
  has_many :discounts
  has_many :uploads
  belongs_to :hall

  has_attached_file :cover_image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :cover_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates_presence_of :name, :venue, :description, :genre, :start, :end, :hall

  GENRES = %w(Dance Traditional Music Comedy Literature)

  # default_scope { where(active: true) }

  # def self.search(search)
  #   if search
  #     where('name LIKE ?', "%#{search}%")
  #   else
  #     scoped
  #   end
  # end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :venue, :genre, :start, :end, :cover_image, :user_id, :bootsy_image_gallery_id, :hall_id, :free_seating, :terms)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for (@event), html: { multipart: true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id , readonly: true  %>
  </div>
  <div class="field">
    <%= f.input :cover_image, as: :file  %>
  </div>
  <div class="field">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.input :venue %>
  </div>
  <div class="field">
    <%= f.label :Hall, required: true %><br>
    <%= f.collection_select(:hall_id, Hall.all, :id, :name, prompt: 'Select Hall') %>
  </div>
  <br>
  <div class="field">
    <%= f.input :free_seating, as: :radio_buttons %>
  </div>
  <div class="field">
    <%= f.input :description, as: :wysihtml5 %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.select :genre, Event::GENRES, required: true, autofocus: true %>
  </div>
  <div class="field">
    <br>
    <%= f.input :terms, as: :wysihtml5 %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <br>
  <div class="actions">
    <%= f.button :submit, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">


<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/events/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<% if can? :create, Event %>
  <%= link_to 'New Event', new_event_path, class: 'btn btn-default' %>
  <%= link_to 'Halls', halls_path, class: 'btn btn-default' %>
  <%= link_to 'Users', user_index_path, class: 'btn btn-default' %>
<% end %>

<h1>Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cover Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Terms</th>
      <th>Genre</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to image_tag(event.cover_image.url(:small)), event.cover_image.url %></td>
        <td><%= event.name %></td>
        <td><%= event.description.html_safe %></td>
        <% if event.terms.nil? %>
          <td><%= event.terms %></td>
        <% else %>
          <td><%= event.terms.html_safe %></td>
        <% end %>
        <td><%= event.genre %></td>
        <td><%= event.start.strftime("%e %b %Y %H:%M:%S%p") %></td>
        <td><%= event.end.strftime("%e %b %Y %H:%M:%S%p") %></td>
        <% if can? :create, event %>
          <td><%= link_to 'Manage Logo', event_uploads_path(event) %></td>
        <% end %>
        <% if can? :create, event %>
          <td><%= link_to 'Manage ticket', event_tickets_path(event) %></td>
        <% end %>
        <% if can? :create, event %>
          <td><%= link_to 'Manage discount', event_discounts_path(event) %></td>
        <% end %>
        <% if can? :update, event %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <% end %>
        <% if can? :destroy, event %>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div style="text-align:center">
  <%= will_paginate @events, renderer: BootstrapPagination::Rails %>
</div>

<br>

</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/events/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/events/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description.html_safe %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @event.terms.html_safe %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @event.genre %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<% if can? :update, @event %>
  <%= link_to 'Edit', edit_event_path(@event) %>
<% end %> |
<%= link_to 'Back', events_path %>

</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>