config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  get "carts/delete_cart/:id" => "carts#delete_cart"
  # get 'store/index'

  resources :halls
  # devise_for :users, :path => '/', controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "/admin" do
    resources :events
    resources :user, :controller => "user"
  end

  resources :events do
    resources :uploads
    resources :tickets
    resources :discounts
  end


  resources :payments

  get "molpay" => "payments#pay_with_molpay"

  post "/payments/:id" => "payments#show"
  post "/hook" => "payments#hook"

  get "/my_tickets" => "tickets#my_tickets"

  get "/assign_tickets" => "tickets#assign_tickets"

  post "/special_checkout" => "line_items#special_checkout"

  put "/subcurator_tickets" => "tickets#subcurator_tickets"

  put "/ticket_update_name" => "tickets#ticket_update_name"

  get "/tickets_customization" => "tickets#tickets_customization"

  get "/my_invoices" => "payments#my_invoices"

  get "/faq" => "store#faq"

  get "store/venue" => "store#venue"

  get "/print_tickets" => "tickets#print_tickets"

  root :to => 'store#index' , :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  # def add_ticket(ticket_id)
  #   current_item = line_items.where(ticket_id: ticket_id).first
  #   if current_item
  #     current_item.quantity += 1
  #   else
  #     current_item = line_items.build(ticket_id: ticket_id)
  #   end
  #
  #   current_item
  # end

  def add_ticket(ticket_id)
    # current_item = line_items.where(ticket_id: ticket_id).first

    @ticket_quantity = self[:quantity].to_i

    @ticket_quantity.each do |tq|
      line_items.build(ticket_id: ticket_id)
    end
  end

  def total_price
    line_items.collect { |item| item.valid? ? item.total_price_after_discount * item.quantity : 0 }.sum
  end

  def cron_job_delete_cart
    cart_time = Time.now - 600
    expired_cart = Cart.where("updated_at < ?", cart_time).where(expired: false)
    expired_cart.destroy_all
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:delete_cart, :show]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @line_items = current_cart.line_items

    @ticket = @line_items.joins(:ticket).select("ticket_id").group("ticket_id").pluck(:ticket_id)

    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart

    # @line_items = LineItem.where(cart_id: @cart)
    #
    # @line_items.each do |li|
    #   li.destroy
    # end

    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  def delete_cart
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<tr>
    <td>
        <div class="thumb_cart">
          <%= link_to image_tag(ticket.event.cover_image.url(:small)), ticket.event.cover_image.url %>
        </div>
         <span class="item_cart"><%= ticket.event.name %><br>
           (<%= ticket.ticket_type %>)</span>
    </td>
    <%= simple_form_for line_item do |f| %>
      <td>
        <% if line_item.ticket.event.free_seating? %>
          Free seating
          <!-- <%= f.label :quantity %>
            <%= f.select :quantity, 1..line_item.remaining_seats_by_quantity, value: line_item.quantity %>
          <td><%= f.submit "Update Qty", class: 'btn btn-primary' %> -->
        <% else %>

          <% @seats = line_item.total_seats.reject{ |e| line_item.all_taken_seat.include? e } %>
          <% if line_item.seat_no == 0 || line_item.seat_no.nil? %>
            <%= f.select :seat_no, @seats, class: 'form-control' %>
            <%= f.submit "Select Seat", class: 'btn btn-primary btn-xs' %>
          <% else %>
            <% unless line_item.ticket.event.free_seating? %>
              <%= line_item.seat_no %>
            <% end %>
          <% end %>

        <% end %>
      </td>
      <td>

          <%= f.hidden_field :ticket_id, value: ticket.id %>

          <%= f.hidden_field :uid %>

          <%= f.input :code, style: 'height: 30px; width: 100px;'%>

          <%= f.submit "Validate", class: 'btn btn-primary btn-xs' %>

      </td>
      <td>
        <% if !line_item.code.nil? %>
          <% if line_item.promo_code.include?(line_item.code) %>
            <%= line_item.discount_percentage %>%
          <% else %>
            0%
          <% end %>
        <% else %>
          0%
        <% end %>
      </td>
      <td>
          <strong><%= number_to_currency line_item.total_price_after_discount %></strong>
      </td>
      <td>
        <%= link_to "", line_item, { data: { confirm: "Are you sure you wish to delete the product '#{line_item.ticket.ticket_type}' from your cart?" }, method: :delete, class: "glyphicon glyphicon-trash" } %>

          <!-- <a href="#"><i class=" icon-trash"></i></a>
          <a href="#"><i class="icon-ccw-2"></i></a> -->
      </td>
    <% end %>
</tr>
      <!-- <h4><%= ticket.event.name %> (<%= ticket.ticket_type %>)</h4>
      <% if line_item.ticket.event.free_seating? %>
        Available : <%= line_item.remaining_seats_by_quantity %> / <%= line_item.ticket.quantity %>
      <% else %>
        Seat No: <%= line_item.seat_no %>
      <% end %> -->

<!--
      <%= simple_form_for line_item do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency line_item.total_price_after_discount %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <% if line_item.ticket.event.free_seating? %> -->
              <!-- <%= f.label :quantity %>
                <%= f.select :quantity, 1..line_item.remaining_seats_by_quantity, value: line_item.quantity %>
              <td><%= f.submit "Update Qty", class: 'btn btn-primary' %> -->
            <!-- <% else %>
              <% @seats = line_item.total_seats.reject{ |e| line_item.all_taken_seat.include? e } %>
              <% if line_item.seat_no == 0 || line_item.seat_no.nil? %>
                <%= f.select :seat_no, @seats %>
                <%= f.submit "Select Seat No", class: 'btn btn-primary' %>
              <% end %>
            <% end %>
            <%= f.hidden_field :ticket_id, value: ticket.id %>
            <%= f.input :code %>
            <%= f.submit "Validate Code", class: 'btn btn-primary' %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= link_to "Delete", line_item, { data: { confirm: "Are you sure you wish to delete the product '#{line_item.ticket.ticket_type}' from your cart?" }, method: :delete, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
      <% end %> -->

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!-- <h2 style="display:inline">Your Cart</h2>&nbsp&nbsp
<%= link_to 'Empty cart' , @cart, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %>
<%= link_to 'Ticket selection', store_url , class: 'btn btn-default' %>

<br><br>
<h5 style="text-align:center">Your ticket purchase session will be kept for ten minutes.
Failing which that ticket will be released and you will have to redo the ticketing process again.
</h5>
<h3 style="text-align:center">

  <div id="timer"></div>
</h3>
<br>
<table class="table"> -->

  <!-- <% for item in @cart.line_items %>
    <%= simple_form_for item do |f|%>
      <tr>
        <td>
          <%= item.ticket.ticket_type %><br></br>
          <% if item.ticket.event.free_seating? %>
            Remaining seats : <%= item.remaining_seats_by_quantity %> / <%= item.ticket.quantity %>
          <% else %>
            Seat No: <%= item.seat_no %>
          <% end %>
        </td>
        <td>Unit price: <%= number_to_currency(item.total_price_after_discount) %></td>
        <td>
          <% if item.ticket.event.free_seating? %>
            <td><%= f.label :quantity %></td>
              <td><%= f.select :quantity, 0..item.remaining_seats_by_quantity, value: item.quantity %></td>
            <td><%= f.submit "Update Qty", class: 'btn btn-primary' %></td>
          <% else %>
            <% seats = item.total_seats.reject{ |e| item.all_taken_seat.include? e } %>
            <% if item.seat_no == 0 || item.seat_no.nil? %>
              <td><%= f.select :seat_no, seats %></td>
              <td><%= f.submit "Select Seat", class: 'btn btn-primary' %></td>
            <% end %>
          <% end %>

        <td><%= f.input :code %></td>
        <td><%= f.submit "Validate Code", class: 'btn btn-primary' %></td>

        </td>
        <td>
          <%= link_to 'Remove ticket', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <%  end %>
  <% end %>

  <tr class="total_line" >
    <td colspan="1" >Total</td>
    <td class="total_cell" ><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>

<%= link_to "Checkout" , new_payment_path, class: 'btn btn-success' %>


<script type="text/javascript">
//start a timer & execute a function every 30 seconds and then reset the timer at the end of 30 seconds.
$('#timer').timer({
    format: '%M minutes %s seconds',
    duration: '10m',
    callback: function() {
        alert('Time up!');
        $('#timer').timer('reset');
    },
    repeat: true //repeatedly call the callback
});
</script> -->


<%= csrf_meta_tags %>
<section id="hero_2">
	<div class="intro_title animated fadeInDown">
           <h1>Place your order</h1>
            <div class="bs-wizard">

                <div class="col-xs-4 bs-wizard-step active">
                  <div class="text-center bs-wizard-stepnum">Your cart</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <%= link_to "", cart_path(@cart), class: 'bs-wizard-dot' %>
                </div>

                <div class="col-xs-4 bs-wizard-step disabled">
                  <div class="text-center bs-wizard-stepnum">Your details</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="payment.html" class="bs-wizard-dot"></a>
                </div>

              <div class="col-xs-4 bs-wizard-step disabled">
                  <div class="text-center bs-wizard-stepnum">Finish!</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="confirmation.html" class="bs-wizard-dot"></a>
                </div>

		</div>  <!-- End bs-wizard -->
    </div>   <!-- End intro-title -->
</section><!-- End Section hero_2 -->

    <div id="position">
    	<div class="container">
        	<ul>
            <li><%= link_to "Home", store_url %></li>
            <li><%= link_to "Event", store_url %></li>
            <li><%= link_to "Cart", @cart %></li>
          </ul>
        </div>
    </div><!-- End position -->

    <div class="container margin_60">
    <div class="row">
    <div class="col-md-8">
    	<table class="table table-striped cart-list add_bottom_30">
            <thead>
            <tr>
                <th>
                    Item
                </th>

                <th>
                    Seat No
                </th>

                <th>
                    Promo code
                </th>
                <th>
                    Discount
                </th>
                <th>
                    Total
                </th>
                <th>
                    Actions
                </th>
            </tr>
            </thead>
						<h5 style="text-align:center">Your ticket purchase session will be kept for ten minutes.
						Failing which that ticket will be released and you will have to redo the ticketing process again.
						</h5>
						<h3 style="text-align:center">

							<div id="timer"></div>
						</h3>
            <tbody>

							<br><br>

							<br>

                <%= link_to 'Empty cart' , @cart, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger pull-right' %>
                <br></br><br>
                <% @line_items.each do |line_item| %>
                  <%= render 'carts/cart_row', ticket: line_item.ticket, line_item: line_item %>
                <% end %>

            </tbody>

            </table>
            <table class="table table-striped options_cart">
            <!-- <thead>
            <tr>
                <th colspan="3">
                    Add options / Services
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td style="width:10%">
                    <i class="icon_set_1_icon-16"></i>
                </td>
                <td style="width:60%">
                    Dedicated Tour guide <strong>+RM34</strong>
                </td>
                <td style="width:35%">
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_1" id="option_1" checked value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-26"></i>
                </td>
                <td>
                    Pick up service <strong>+RM34*</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_2" id="option_2" value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-71"></i>
                </td>
                <td>
                    Insurance <strong>+RM24*</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_3" id="option_3" value="" checked>
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-15"></i>
                </td>
                <td>
                    Welcome bottle <strong>+RM24</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_4" id="option_4" value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-59"></i>
                </td>
                <td>
                    Coffe break <strong>+RM12*</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_5" id="option_5" value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-58"></i>
                </td>
                <td>
                    Dinner <strong>+RM26*</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_6" id="option_6" value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="icon_set_1_icon-40"></i>
                </td>
                <td>
                    Bike rent <strong>+RM26*</strong>
                </td>
                <td>
                    <label class="switch-light switch-ios pull-right">
                    <input type="checkbox" name="option_7" id="option_7" value="">
                    <span>
                    <span>No</span>
                    <span>Yes</span>
                    </span>
                    <a></a>
                    </label>
                </td>
            </tr>
            </tbody> -->
            </table>
            <!-- <small>* Prices for person.</small> -->
    </div><!-- End col-md-8 -->

    <aside class="col-md-4">
    <div class="box_style_1">
        <h3 class="inner">- Summary -</h3>
        <table class="table table_summary">
        <tbody>
          <% @ticket.each do |ticket| %>
          <tr>
            <td>
              <%= Ticket.find(ticket).ticket_type %>
            </td>
            <td class="text-right">
              <%= @line_items.where(ticket_id: ticket).pluck(:quantity).sum %>
            </td>
          </tr>
          <% end %>
        <tr class="total">
          <td>
              Total cost
          </td>
          <td class="text-right">
            RM<%= @cart.total_price %>
          </td>
        </tr>
        </tbody>
        </table>

				<% if @cart.total_price == 0 && (current_user.curator? || current_user.admin? || current_user.subcurator?) %>
					<%= link_to "Special check out" , special_checkout_path, method: :post, class: 'btn_full' %>
				<% end %>
        <%= link_to "Check out" , new_payment_path, class: 'btn_full' %>
        <%= link_to "Continue" , store_url, class: 'btn_full_outline icon-right' %>
    </div>
    <div class="box_style_4">
        <i class="icon_set_1_icon-57"></i>
        <h4>Need <span>Help?</span></h4>
        <a href="tel://004542344599" class="phone">+45 423 445 99</a>
        <small>Monday to Friday 9.00am - 7.30pm</small>
    </div>
    </aside><!-- End aside -->

</div><!--End row -->
</div><!--End container -->


<div id="toTop"></div><!-- Back to top button -->

<%= javascript_include_tag 'timer.jquery.js' %>

<script type="text/javascript">

$('#timer').timer({
		format: '%M minutes %s seconds',
		duration: '10m',
		callback: function() {
				alert('Time up! You cart will be deleted now ! You will be redirected to home page. ');
				$.ajax({
					url: "/carts/delete_cart/" + <%= @cart.id %>,
					type: "get",
					data: {"_method":"delete"}
				});
		}
});

$(document).ajaxStop(function(){
    document.location.href = '/';
});

</script>





  </body>
</html>