config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  get "carts/delete_cart/:id" => "carts#delete_cart"
  # get 'store/index'

  resources :halls
  # devise_for :users, :path => '/', controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "/admin" do
    resources :events
    resources :user, :controller => "user"
  end

  resources :events do
    resources :uploads
    resources :tickets
    resources :discounts
  end


  resources :payments

  get "molpay" => "payments#pay_with_molpay"

  post "/payments/:id" => "payments#show"
  post "/hook" => "payments#hook"

  get "/my_tickets" => "tickets#my_tickets"

  get "/assign_tickets" => "tickets#assign_tickets"

  post "/special_checkout" => "line_items#special_checkout"

  put "/subcurator_tickets" => "tickets#subcurator_tickets"

  put "/ticket_update_name" => "tickets#ticket_update_name"

  get "/tickets_customization" => "tickets#tickets_customization"

  get "/my_invoices" => "payments#my_invoices"

  get "/faq" => "store#faq"

  get "store/venue" => "store#venue"

  get "/print_tickets" => "tickets#print_tickets"

  root :to => 'store#index' , :as => 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :cart
  belongs_to :payment

  validates :quantity, :seat_no, presence: true

  def total_price_after_discount
    discount = Discount.where ticket_id: ticket.id
    if !discount.nil?
      discount = discount.pluck(:code)
      if discount.include?(self[:code])
        percentage = Discount.find_by(code: self[:code])
        initial_amount = (ticket.price).to_f
        discounted_total = initial_amount * (percentage.discount_percentage.to_f / 100)
        initial_amount - discounted_total
      else
        ticket.price
      end
    else
      ticket.price
    end
  end

  def total_seats
    (ticket.min_seat_no.to_i..ticket.max_seat_no.to_i).to_a
  end

  def remaining_seats_by_quantity
    line_items = LineItem.where(ticket_id: ticket_id)
    total_taken_seat = line_items.collect { |li| li.valid? ? (li.quantity) : 0 }.sum
    ticket.quantity.to_i - total_taken_seat.to_i
  end

  # for ticket * quantity
  def ticket_quantity
    line_items = LineItem.where(ticket_id: ticket_id)
    total_taken_seat = line_items.collect { |li| li.valid? ? (li.quantity) : 0 }.sum
  end

  def all_taken_seat
    line_items = LineItem.where(ticket_id: ticket_id)
    line_items.pluck(:seat_no)
  end

  def booking_quantity_cannot_be_greater_than_total_quantity
  	if self.quantity.to_i > ticket.quantity.to_i
      errors.add(:quantity, "can't be greater than total quantity")
    end
  end

  def discount_percentage
    Discount.find_by(code: self[:code]).discount_percentage
  end

  def promo_code
    Discount.where(ticket_id: ticket.id).pluck(:code)
  end

  # def receipt
  #   Receipts::Receipt.new(
  #     id: payment_id,
  #     product: "Tickets",
  #     company: {
  #       name: "Diversecity",
  #       address: "Jalan Damansara 10, Malaysia",
  #       email: "admin@diversecity",
  #       logo: Rails.root.join("app/assets/images/diversecity.png")
  #     },
  #     line_items: [
  #       # ["Date",           line.created_at.strftime("%e %b %Y %H:%M:%S%p")],
  #       # ["Account Billed", "#{payment.user.name} (#{payment.user.email})"],
  #       ["Buyer Name", User.find(self.user_id).name],
  #       ["Event", self.ticket.event.name],
  #       ["Tickets Quantity", self.quantity],
  #       ["Seat No", self.seat_no],
  #       ["Transaction ID", self.uid]
  #     ]
  #   )
  # end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    # @my_tickets = LineItem.where user_id: current_user.id
    # # @event = @my_tickets
    #  respond_to do |format|
    #    format.html
    #    format.pdf do
    #      pdf = PrintTicket.new(@my_tickets)
    #      send_data pdf.render, filename: "ticket_#{@line_item.uid}",
    #                            type: "application/pdf",
    #                            disposition: "inline"
    #    end
    #  end
  end


  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # def my_tickets
  #   if current_user.curator? || current_user.admin?
  #     @my_tickets = LineItem.where user_id: current_user.id
  #   else
  #     @my_tickets = LineItem.joins(:payment).where(payments: { user_id: current_user })
  #   end
  # end

  def special_checkout
    @line_items = current_cart.line_items

    @line_items.each do |li|
      li.update_attributes special_checkout: true, user_id: current_user.id
    end

    current_cart.update_attributes expired: true
    session[:cart_id] = nil

    redirect_to my_tickets_path, notice: 'Ticket was successfully bought through special checkout'
  end

  # def promo
  #   @cart = current_cart
  #   @line_item = LineItem.where(cart: @cart.id, id: self_id)
  #
  #   @line_item.update_attributes code: params[:code]
  #   redirect_to @line_item.cart
  #   # ticket = Ticket.find(params[:ticket_id])
  #   #
  #   # discount = Discount.find_by ticket_id: ticket.id
  #   # if discount.code == params[:code]
  #   #   asd
  #   #   (ticket.price * quantity).to_f * (discount.discount_percentage.to_f / 100)
  #   # else
  #   #   ticket.price * quantity
  #   # end
  #
  # end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    @seating = Ticket.find(params[:line_item][:ticket_id]).event
    @ticket = Ticket.find(params[:line_item][:ticket_id])

    # @run = LineItem.new(params[:run])
    # @tape_ids = @run.add_ticket(params[:run][:tapes])

    # if !@seating.free_seating?
      # @line_item = @cart.add_ticket(@ticket.id)
    # else

    @quantity = (params[:line_item][:quantity]).to_i
    @quantity.times do
      @uid = SecureRandom.hex(10)
      @line_item = @cart.line_items.build(ticket: @ticket, uid: @uid)
    # end
      @line_item.save
    end

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Ticket was successfully added to your cart.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item.cart, notice: 'Ticket was successfully updated in your cart.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { redirect_to @line_item.cart, alert: 'Seat already taken' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @line_item.cart, notice: 'Ticket was successfully removed from your cart.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:ticket_id, :cart_id, :quantity, :code, :seat_no, :uid)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :ticket_id %>
    <%= f.input :cart_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.ticket_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/my_tickets.html.erb
<section id="hero_2">
	<div class="intro_title animated fadeInDown">

    </div>   <!-- End intro-title -->
</section><!-- End Section hero_2 -->

    <div id="position">
    	<div class="container">
        	<ul>
            <li><%= link_to "My Tickets", my_tickets_path %></li>
          </ul>
        </div>
    </div><!-- End position -->

    <div class="container margin_60">
	<div class="row">
		<div class="col-md-8">

			<div class="form_title">
				<h3><strong><i class="icon-tag-1"></i></strong>My Tickets</h3>
				<p>
					Print your tickets here
				</p>
			</div>
			<div class="step">

        <table class="table">
          <thead>
            <tr>
              <th>Event</th>
              <th>Ticket</th>
              <th>Quantity</th>
              <th>Seat No / Free seating</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% @my_tickets.each do |mt| %>
              <tr>
                <td><%= mt.ticket.event.name %></td>
                <td><%= mt.ticket.ticket_type %></td>
                <td><%= mt.quantity %></td>
                <td>
                  <% if mt.seat_no == 0 || mt.seat_no.nil? %>
                    Free Seating
                  <% else %>
                    <%= mt.seat_no %>
                  <% end %>
                </td>
                <td><%= link_to "Print Ticket", line_item_path(mt.id, format: :pdf), target: '_blank' %>
              </tr>
            <% end %>
          </tbody>
        </table>


			</div><!--End step -->
		</div><!--End col-md-8 -->

	</div><!--End row -->
</div>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @line_item.ticket_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>